language: python
# python versions
matrix:
  include:
  - python: "2.7"
    env: CELERY_VERSION=3.1
  - python: "2.7"
    env: CELERY_VERSION=4.0
  - python: "2.7"
    env: CELERY_VERSION=4.1
  - python: "3.3"
    env: CELERY_VERSION=3.1
  - python: "3.4"
    env: CELERY_VERSION=3.1
  - python: "3.4"
    env: CELERY_VERSION=4.0
  - python: "3.4"
    env: CELERY_VERSION=4.1
  - python: "3.5"
    env: CELERY_VERSION=3.1
  - python: "3.5"
    env: CELERY_VERSION=4.0
  - python: "3.5"
    env: CELERY_VERSION=4.1
  - python: "3.6"
    env: CELERY_VERSION=4.1
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install celery==$CELERY_VERSION requests ephem
  - pip install codecov
# command to run tests
script: pytest
# combinations to include
after_success:
  - codecov
