language: python
# python versions
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# celery versions
env:
  - CELERY_VERSION=3.0
  - CELERY_VERSION=3.1
  - CELERY_VERSION=4.0
  - CELERY_VERSION=4.1
# command to install dependencies
install:
  - pip install celery==$CELERY_VERSION requests ephem
# command to run tests
script: pytest
# combinations to include
matrix:
  include:
  - python: "2.7"
    env: CELERY_VERSION=3.1
  - python: "2.7"
    env: CELERY_VERSION=4.0
  - python: "2.7"
    env: CELERY_VERSION=4.1
  - python: "3.3"
    env: CELERY_VERSION=3.1
  - python: "3.4"
    env: CELERY_VERSION=3.1
  - python: "3.4"
    env: CELERY_VERSION=4.0
  - python: "3.4"
    env: CELERY_VERSION=4.1
  - python: "3.5"
    env: CELERY_VERSION=3.1
  - python: "3.5"
    env: CELERY_VERSION=4.0
  - python: "3.5"
    env: CELERY_VERSION=4.1
  - python: "3.6"
    env: CELERY_VERSION=4.1
